server:
  port: 8090

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

  # Gmail Configuration
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:nguyenkimtruongk4@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:ikhoxsoliwoezlik}
