server:
  port: 8089

spring:
  application:
    name: payment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/payment_service?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:truong22022004}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: payment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

# VNPay Sandbox Default Config (can be overridden in docker-compose)
vnpay:
  tmnCode: ${VNP_TMNCODE:YQ8390LF}
  hashSecret: ${VNP_HASHSECRET:56FZJSHHPFXCCXBXVHT9HL0J9W8RWG3T}
  url: ${VNP_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  returnUrl: ${VNP_RETURNURL:http://localhost:8089/api/payment/vnpay-callback}
